build: off

environment:
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'

install:
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe